# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Samuel B. Inman
email:
description: >- # this means to ignore newlines until "baseurl:"
 Extending structural and electrochemical materials—and improving the lives of those who depend on them.
linkedin_username: samuel-b-inman
scholar: "bAFenwEAAAAJ&hl"
minimal_mistakes_skin: sunrise
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Denver # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

main:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Research"
    url: /research/
  - title: "Publications"
    url: /publications/
  - title: "Teaching"
    url: /teaching/
  - title: "CV"
    url: /cv/
  
author:
  name   : "Samuel B Inman"
  avatar : "/assets/images/Headshot.jpg"
  bio    : "Ensuring structural and electrochemical materials are made to last"
  links:
    - label: "Email"
      icon: "far fa-fw fa-envelope"
      url: "mailto:&#105;&#110;&#109;&#097;&#110;&#046;&#115;&#097;&#109;&#117;&#101;&#108;&#046;&#098;&#064;&#103;&#109;&#097;&#105;&#108;&#046;&#099;&#111;&#109;"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/samuel-b-inman/"
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google"
      url: "https://scholar.google.com/citations?user=bAFenwEAAAAJ&hl=en"
    - label: "Orcid"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0002-2535-4150"

header:
  logo:
    text: "Samuel B. Inman"
  links:
    - title: "About"
      url: /about/
    - title: "Publications"
      url: /publications/
    - title: "Teaching"
      url: /teaching/
    - title: "CV"
      url: /cv/
      
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/samuel-b-inman/"
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google"
      url: "https://scholar.google.com/citations?user=bAFenwEAAAAJ&hl=en"
    - label: "Orcid"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0002-2535-4150"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: page
      author_profile: true
      sidebar: false
      
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
